### ISSUE TITLE
No way of setting attributes on the Input.text element

### ISSUE THREAD

**Issue by valberg** [FabHof/elm-ui-datepicker#2]
First of, reeeally nice that you've created this package for elm-ui. I've needed this a couple of times, but the effort to write something myself didn't fit into my time constraints!

Thanks! :+1: 

So, my issue is about setting attributes on the `Input.text` element here: https://github.com/FabHof/elm-ui-datepicker/blob/1.0.0/src/DatePicker.elm#L381

I'm using a special style for my forms and sadly I can't fit the datepicker into that.

Maybe `Settings` could include a `inputAttributes` field which is added to the list beginning on line 382 (https://github.com/FabHof/elm-ui-datepicker/blob/1.0.0/src/DatePicker.elm#L382)?

**Comment by FabHof** [comment]
You are right, this is missing. I fear that this could interfere with the attributes that are required for the date picker to work and it could lead to unexpected behavior.

I will have to think about this and at least document any unexpected behavior.

**Comment by FabHof** [comment]
@valberg #3 should fix this. The wrapper is removed, so the attributes are directly on the `Input.text`. However some Events are not usable, because they are used internally by the date picker. 

I would love some feedback on this idea.

**Comment by valberg** [comment]
@FabHof Very nice indeed! I think it's not a problem, until it becomes a problem for someone ;) My desire was just to be able to style the input field.
