### ISSUE TITLE
Cannot install package: "the hash of the archive has changed since publication"

### ISSUE THREAD

**Issue by tlinnanv** [FabHof/elm-ui-datepicker#8]
Thank you @fabhof for your work on Elm! 

When installing I get the following error:
```
-- CORRUPT PACKAGE DATA --------------------------------------------------------

I downloaded the source code for fabhof/elm-ui-datepicker 4.0.0 from:

    https://github.com/fabhof/elm-ui-datepicker/zipball/4.0.0/

But it looks like the hash of the archive has changed since publication:

  Expected: a196df6cf7e31b523f53094e2c5fff870897bab8
    Actual: b73b6a1259666a106c78a4fb730232ea8facbd57

This usually means that the package author moved the version tag, so report it
to them and see if that is the issue. Folks on Elm slack can probably help as
well.
```

In order to reproduce:
```
mkdir elm-test
cd elm-test
elm init
elm install fabhof/elm-ui-datepicker
```
(I did `rm -r ~/.elm` in order to force the download)

I found mentions of this happening if the package author changes their GitHub username but this doesn't seem to be the case.

Also I found this issue from beginning of February that reports similar issues on other packages due to Github internal changes but this seems to be resolved by GitHub already: https://discourse.elm-lang.org/t/potential-breaking-change-in-github-zipballs-codec/8121/2. And my Elm project has around 30 dependencies and this is the only package that gives the error if I remove the `~/.elm` folder and then run `elm make`.  So it doesn't seem like the above issue coming up again.

I'm at a loss here on what I can do/try on my side. Tested on 2 machines (Windows & Linux) and this happens on both of them.

**Comment by FabHof** [comment]
That was interesting to find out. Try again please and let me know if it is still an issue for you.

**Comment by mackdunkan** [comment]
I also got this error

**Comment by FabHof** [comment]
@mackdunkan Still get it?

**Comment by tlinnanv** [comment]
Works here now! Thanks for the fix, what did you do?

**Comment by esurat20** [comment]
Works well for now. Thanks for fixing @FabHof.

**Comment by mackdunkan** [comment]
Thanks for fixing @FabHof
